# Pandas

## Building Blocks of Pandas

- Index: Axis labels used to align data across columns; Analogy: Row index or Primary Key
- Series: 1-D labelled array; Analogy: Excel or SQL Column 
- Dataframe: 2-D labeled table; Analogy: Excel sheet or SQL table

Handline Missing Values in Dataframes

In [2]:
import pandas as pd

In [4]:
df1 = pd.DataFrame({
    "Category": ["Cat1", "Cat2", "Cat3"]
})

print(df1)

  Category
0     Cat1
1     Cat2
2     Cat3

## File input/output Pandas
Pandas can read data from multiple sources: csv, excel, json, sql

df = pd.read_csv("data.csv")
df = pd.read_excel("data.xslx")

Key features:
- Possible to select specific columns while reading data
- Possible to export select columns by passing a list of columns vis columns parameter
- Write to target

## View, Copies, and Inplace Operations

In [9]:
# If a dataframe object is assigned to another variable, the second variable gets reference to same object instance
df = pd.DataFrame({
    "Hello":[ "World!" ]
})

print(df)

df1 = df

df1["Hello"] = ["Advika!"]

print(df)

    Hello
0  World!
     Hello
0  Advika!

In [ ]:
# Creates a different object instance with copy
df1 = df.copy()

# Now this assignment does not overwrites original data-frame
df1["Hello"] = ["World!"]

print(df)

     Hello
0  Advika!

### Even in case Column selection, Slicing, Filtering using loc or iloc - view is returned

### Best practices:
- Selection, Slicing, Filtering using loc or iloc - view is returned
- Use copy method explicitly for creating a copy
- _is_view method to check if a variable is a copy or view

In [ ]:

df1 = df

df1._is_view

True

In [14]:
df1 = df.copy()

df1._is_view

False

### Inplace operations in Dataframes
- Inplace operation refers to modifying an existing dataframe without returning new object
- inplace=True parameter
- Note: Does NOT happen at memory level and pandas creates a new object and reassigns it to same variable
- When to use:
  - When wiring data cleaning pipelines, original data-set not required
  - When memory is not a major concern
- When not to use:
  - When original data is not required
  - When concise code needs to be created

In [16]:
import numpy as np

df = pd.DataFrame({
    "Department": ["Sales", "Sales", "HR", "IT", None, "Sos"],
    "Employee": ["Asha", "Bala", "Chetan", None, "Esha", "Usha"],
    "Salary": [50,55,50,53,60, np.nan]
})

df.dropna()
df

  Department Employee  Salary
0      Sales     Asha    50.0
1      Sales     Bala    55.0
2         HR   Chetan    50.0
3         IT     None    53.0
4       None     Esha    60.0
5        Sos     Usha     NaN

## Setting / Updating Values in DataFrame

- Set value to a single cell, multiple cells at once, entire column at once
- Set or update values using:
  - Label based assignment with .loc[] or .at[]
  - Position based assignment with .iloc[] or .iat[]
  - Conditional assignment
  - Vectorized assignment
- Tips:
  - Vectorised assignment preferred
  - Label based updates preferred

**Note** : Pandas sometimes copy and sometimes views and is unpredictable in nature.

In [18]:
df.loc[1, "Marks"] = 65

df

  Department Employee  Salary  Marks
0      Sales     Asha    50.0    NaN
1      Sales     Bala    55.0   65.0
2         HR   Chetan    50.0    NaN
3         IT     None    53.0    NaN
4       None     Esha    60.0    NaN
5        Sos     Usha     NaN    NaN

In [20]:
df.loc[df["Department"]=="Sales", "Salary"] += 10

df

  Department Employee  Salary  Marks
0      Sales     Asha    70.0    NaN
1      Sales     Bala    75.0   65.0
2         HR   Chetan    50.0    NaN
3         IT     None    53.0    NaN
4       None     Esha    60.0    NaN
5        Sos     Usha     NaN    NaN

In [25]:
df1 = df.copy()

df1["Marks"] = df1["Department"].where(df1['Marks'] == None, 45)

df1

  Department Employee  Salary Marks
0      Sales     Asha    70.0    45
1      Sales     Bala    75.0    45
2         HR   Chetan    50.0    45
3         IT     None    53.0    45
4       None     Esha    60.0    45
5        Sos     Usha     NaN    45

In [26]:
import numpy as np

df = pd.DataFrame({
    "Department": ["Sales", "Sales", "HR", "IT", None, "Sos"],
    "Employee": ["Asha", "Bala", "Chetan", None, "Esha", "Usha"],
    "City": ['Hyd','Del', 'Chn', 'Pat', 'Ran', 'Ahm']
})

df['City'] = df["City"].replace({'Hyd': 'Hyderabad', 'Chn': 'Chennai'})
df['City'] = df["City"].replace({'Del': 'Delhi', 'Pat': 'Patna', 'Ran': 'Ranchi', 'Ahm': 'Ahmedabad'})

df

  Department Employee       City
0      Sales     Asha  Hyderabad
1      Sales     Bala      Delhi
2         HR   Chetan    Chennai
3         IT     None      Patna
4       None     Esha     Ranchi
5        Sos     Usha  Ahmedabad

## Splitting Data into Groups

- groupby() operation allows:
  - Split data into groups
  - Apply a function
  - Combine results into a new DataFrame
- Aggregation functions:
  - Grouped data can be aggregated using built-in functions (mean, sum, count, min, max, etc)
  - Multiple aggregations per group
  - Custom Functions and Lambda functions

In [27]:
df = pd.DataFrame({
    "Department": ["Sales", "Sales", "HR", "IT", "HR", "Sos"],
    "Employee": ["Asha", "Bala", "Chetan", "Rohit", "Esha", "Usha"],
    "City": ['Hyd','Del', 'Chn', 'Pat', 'Ran', 'Ahm'],
    "Experience": [1,2,3,4,5,6]
})

In [29]:
grouped = df.groupby("Department")

grouped.groups

{'HR': [2, 4], 'IT': [3], 'Sales': [0, 1], 'Sos': [5]}

In [30]:
grouped.get_group('HR')

  Department Employee City  Experience
2         HR   Chetan  Chn           3
4         HR     Esha  Ran           5

In [ ]:
grouped["Experience"].agg("sum")

Department
HR       8
IT       4
Sales    3
Sos      6
Name: Experience, dtype: int64

In [33]:
grouped["Experience"].agg(["mean", "sum"])

            mean  sum
Department
HR           4.0    8
IT           4.0    4
Sales        1.5    3
Sos          6.0    6

In [34]:
def range(x):
    return x.max() - x.min()

grouped["Experience"].agg(["mean", "sum", range])

            mean  sum  range
Department
HR           4.0    8      2
IT           4.0    4      0
Sales        1.5    3      1
Sos          6.0    6      0

In [36]:
grouped.filter(lambda x: (x["Experience"]>= 2).any())

  Department Employee City  Experience
0      Sales     Asha  Hyd           1
1      Sales     Bala  Del           2
2         HR   Chetan  Chn           3
3         IT    Rohit  Pat           4
4         HR     Esha  Ran           5
5        Sos     Usha  Ahm           6

In [37]:
grouped.filter(lambda x: (x["Experience"]>= 2).all())

  Department Employee City  Experience
2         HR   Chetan  Chn           3
3         IT    Rohit  Pat           4
4         HR     Esha  Ran           5
5        Sos     Usha  Ahm           6

## Handling Categories in DataFrames
- Special datatypes in pandas for categorical values
- Efficient for:
  - Repeated String values
  - Faster grouping, sorting, and filtering
- Define category order when comparisons are meaningful
  - Ex: Low, Medium, High

In [39]:
df = pd.DataFrame({
    "Region": ["East", "West", "North", "South"]
})
print(df["Region"].dtype)
df["Region"] = df["Region"].astype("category")
print(df["Region"].dtype)

object
category

In [42]:
df["Region"].cat.categories

Index(['East', 'North', 'South', 'West'], dtype='object')

In [43]:
df["Region"] = df["Region"].cat.rename_categories({"East": 'E', "West": 'W', "North": 'N', "South": 'S'})

In [44]:
df["Region"].cat.categories

Index(['E', 'N', 'S', 'W'], dtype='object')

In [45]:
df["Region"] = df["Region"].cat.reorder_categories(['E', 'W', 'N', 'S'], ordered=True)
df["Region"].cat.categories

Index(['E', 'W', 'N', 'S'], dtype='object')

In [47]:
df["Region"] = df["Region"].cat.add_categories(['NE', 'NW', 'SW', 'SE'])
df["Region"].cat.categories

Index(['E', 'W', 'N', 'S', 'NE', 'NW', 'SW', 'SE'], dtype='object')

## Handling Missing Values in DataFrames

- Missing values in Pandas are represented by:
  - NaN : Not a number
  - NaT : Not a Time
  - None: For object/string columns
- Treated as missing indicators by Pandas  
- Standard methods:
  - df.isna() & df.notna()
  - df.info()

In [51]:
df = pd.DataFrame({
    "Name": ["Ankit", "Advika", "Arshika", "Shrija", "Kuchhum", "Puchhu", "Prasit"],
    "Marks": [np.nan, 99, 99, 97, 95, 99, 100],
    "City": [np.nan, "BGL", "BGL", "PUN", "GGN", "GGN", "PAT"]
})

df

      Name  Marks City
0    Ankit    NaN  NaN
1   Advika   99.0  BGL
2  Arshika   99.0  BGL
3   Shrija   97.0  PUN
4  Kuchhum   95.0  GGN
5   Puchhu   99.0  GGN
6   Prasit  100.0  PAT

In [52]:
df["Marks"] = df["Marks"].fillna(df["Marks"].mean())

df

      Name       Marks City
0    Ankit   98.166667  NaN
1   Advika   99.000000  BGL
2  Arshika   99.000000  BGL
3   Shrija   97.000000  PUN
4  Kuchhum   95.000000  GGN
5   Puchhu   99.000000  GGN
6   Prasit  100.000000  PAT