# Pandas Datetime

In [1]:
import pandas as pd

## Pandas Date-Time

In [ ]:
# pd.to_datetime

## Pandas Date-Range

In [4]:
# pd.date_range
pd.date_range(start="2024-01-01", periods=10, freq="15D")

DatetimeIndex(['2024-01-01', '2024-01-16', '2024-01-31', '2024-02-15',
               '2024-03-01', '2024-03-16', '2024-03-31', '2024-04-15',
               '2024-04-30', '2024-05-15'],
              dtype='datetime64[ns]', freq='15D')

In [5]:
pd.date_range(start="2024-01-01", periods=10, freq="ME")

DatetimeIndex(['2024-01-31', '2024-02-29', '2024-03-31', '2024-04-30',
               '2024-05-31', '2024-06-30', '2024-07-31', '2024-08-31',
               '2024-09-30', '2024-10-31'],
              dtype='datetime64[ns]', freq='ME')

In [6]:
pd.date_range(start="2024-01-01", periods=10, freq="MS")

DatetimeIndex(['2024-01-01', '2024-02-01', '2024-03-01', '2024-04-01',
               '2024-05-01', '2024-06-01', '2024-07-01', '2024-08-01',
               '2024-09-01', '2024-10-01'],
              dtype='datetime64[ns]', freq='MS')

In [11]:
pd.date_range(start="2024-01-01", periods=10, freq=pd.offsets.Day(5))

DatetimeIndex(['2024-01-01', '2024-01-06', '2024-01-11', '2024-01-16',
               '2024-01-21', '2024-01-26', '2024-01-31', '2024-02-05',
               '2024-02-10', '2024-02-15'],
              dtype='datetime64[ns]', freq='5D')

## Sorting and Ranking Dataframes

In [15]:
df = pd.DataFrame({
    "Score_A": [30,12,45,33],
    "Score_B": [100,101,102,90]
})

df['Rank_A_Avg'] = df['Score_A'].rank(method="average")
df

   Score_A  Score_B  Rank_A_Avg
0       30      100         2.0
1       12      101         1.0
2       45      102         4.0
3       33       90         3.0

In [17]:
df['Rank_B_Avg'] = df['Score_B'].rank(method="min")
df

   Score_A  Score_B  Rank_A_Avg  Rank_B_Avg
0       30      100         2.0         2.0
1       12      101         1.0         3.0
2       45      102         4.0         4.0
3       33       90         3.0         1.0

## Descriptive Statistics on DataFrames
- Central Tendency (mean, median, mode)
- Spread (std dev, etc)
- Relationships (corelations)

In [ ]:
# describe
# coor
# median

## Concatenation of dataframes vertically

In [24]:
# pd.concat
df1 = pd.DataFrame({
    "Key1": ["Val1", "Val2", "Val3", "Val4"]
    })

df2 = pd.DataFrame({
    "Key1": ["Val5", "Val6"]
    })

print(df1)
print(df2)
print(pd.concat([df1, df2]))
print(pd.concat([df1, df2], axis=1))

   Key1
0  Val1
1  Val2
2  Val3
3  Val4
   Key1
0  Val5
1  Val6
   Key1
0  Val1
1  Val2
2  Val3
3  Val4
0  Val5
1  Val6
   Key1  Key1
0  Val1  Val5
1  Val2  Val6
2  Val3   NaN
3  Val4   NaN