# Lambda Functions
- A lambda is a short, one-line function without a name and referred to as anonymous function
- Defined using the keyword lambda, followed by parameters and expression
    Ex: lambda x: x**2
- Expression after : is automatically returned - no return keyword needed
- Commonly used to create a conditional rule without defining a full function
    Ex: nums = [3,5,8,10]
    list(filter(lambda x: x%2 == 0, nums))
- Can be used along with if/else condition and for loops as well
- Note: Ise lamda functions only for inline one-time transformations
- Widely used in feature creation, aggregation, and preprocessing steps of Machine Learning

In [3]:
# Traditional approach for function declaration
def square_(a: int):
    return a**2
print(square_(5))

# Lambda approach
square_lambda = lambda x: x**2
print(square_lambda(5))

# Lambda direct call
print((lambda x: x**2)(5))

# Lambda with multiple parameters
print((lambda x,y: x**2+y**2)(2,3))

25
25
25
13

## Lambda based filters

In [ ]:
nums = [3, 5, 8, 10]

list(filter(lambda x: x%2==0, nums))

[8, 10]

In [12]:
nums = [('a', 1), ('b', 2), ('c', 4)]
dict(filter(lambda x: x[1]%2==0, nums))

{'b': 2, 'c': 4}

# Pandas

## Building Blocks of Pandas
- Index = Axis labels, Row Index or Primary Key, Automatically assigns integer index; immutable object and can be given a name
- Series = 1-D labeled array. Excel or SQL Column 
- DataFrame = 2-D labeled table -> collection of Series sharing an index; Excel Sheet or SQL Table. Assigning datatype to column is efficient in terms of memory and speed.

In [13]:
import pandas as pd
import numpy as np

In [14]:
s = pd.Series([3,5,7,9,11])
print(s)

0     3
1     5
2     7
3     9
4    11
dtype: int64

In [16]:
df = pd.DataFrame({
    "Name": ["Ankit", "is", "here"],
    "Age": [23,24,25],
    "Score": [91,93,95]
})

df

    Name  Age  Score
0  Ankit   23     91
1     is   24     93
2   here   25     95

In [21]:
df1 = pd.DataFrame({"Marks": [85,90,95], "Names":['Ankit', "Ank", "It"]}, index=["A1", "A2", "A3"])
df1.index.name = "RollNumber"
df1

            Marks  Names
RollNumber
A1             85  Ankit
A2             90    Ank
A3             95     It

# Selecting / Filtering DataFrame by Labels

- .loc[] selects data by labels.
- Syntax: df.loc[row_labels, column_labels]
- .loc accepts:
    - Single label -> df.loc["row", "col"]
    - List of labels -> df.loc[["row1", "rown"], ["col1", "cown"]]
    - Label range -> df.loc["row1": "row3"]
    - Boolean conditions -> df.loc[df["col2"]>80, ["col1", "col2"]]

In [24]:
df1 = pd.DataFrame({"Marks": [85,90,95], "Names":['Ankit', "Ank", "It"]}, index=["A1", "A2", "A3"])
df1.loc[["A1", "A3"]]

    Marks  Names
A1     85  Ankit
A3     95     It

In [25]:
df1.loc[["A1"],"Names"]

A1    Ankit
Name: Names, dtype: object

In [26]:
df1.loc[["A2"], ["Names", "Marks"]]

   Names  Marks
A2   Ank     90

In [30]:
# Using Lambda
df1.loc[lambda x: x["Marks"]>=90]

    Marks Names
A2     90   Ank
A3     95    It

In [43]:
df1.loc[lambda x: x["Names"]=="Ank",["Names"]]

   Names
A2   Ank

## Selecting / Filtering DataFrame by Position
- .iloc[] selects data by position like Python lists
- Syntax: df.iloc[row_position, col_position]
- iloc accepts:
    - Single integer df.iloc[0,1]
    - List of integers df.iloc[[0,2], [1,2]]
    - Slice ranges (end excluded) -> df.iloc[0:3, 0:2]
    - Boolean arrays -> df.iloc[[True, False, True, False],:]

In [46]:
# Select specific index using loc
print(df1)
df1.iloc[1,1]

    Marks  Names
A1     85  Ankit
A2     90    Ank
A3     95     It

'Ank'

In [ ]:
# Negative Index
df1.iloc[-1:]

    Marks Names
A3     95    It

In [51]:
df1.iloc[-1:-1]

Empty DataFrame
Columns: [Marks, Names]
Index: []

In [ ]:
# Reverse order
df1.iloc[::-1]

    Marks  Names
A3     95     It
A2     90    Ank
A1     85  Ankit

In [ ]:
# Reverse row and column order
df1.iloc[::-1, ::-1]

    Names  Marks
A3     It     95
A2    Ank     90
A1  Ankit     85

## Selecting / Filtering using query
- Use .query to conditionally filter rows in a DataFrame when:
    - Need cleaner, more readable code than chained indexes
    - Need complex logical conditions involving multiple columns
    - Need to avod repetitive df[] syntax
    - Need dynamical filter based on the values of a variable

- Do not use Query in following scenarios:
    - Column names have spaces or special characters
    - When performance is critical

In [56]:
df1.query("Marks >= 90")

    Marks Names
A2     90   Ank
A3     95    It

In [ ]:
# Apply query and then apply Column selection
df1.query("Marks >= 90")[["Names"]]

   Names
A2   Ank
A3    It

In [ ]:
# Query based on parameter passing and external variables
name= "Ankit"
df1.query("Names == @name")

    Marks  Names
A1     85  Ankit

In [ ]:
# Multi combination of query
name= "Ank"
df1.query("Names == @name and Marks>=90 ")

    Marks Names
A2     90   Ank

In [64]:
# Parameterized query
name= "Ank"
marks = 90
df1.query("Names == @name or Marks>=@marks ")

    Marks Names
A2     90   Ank
A3     95    It